/* Automatically generated by 'helper/gen-api.js' */

import login from './modules/login'

/**
 * @params module
 */
function useHttp(module) {
  switch (module) {
    case 'login':
      return login
  }
}
export default useHttp
